### ISSUE TITLE
"last updated on May 20th, 2014" cannot be correct

### ISSUE THREAD

**Issue by felixrabe** [garethr/vagrantboxes-heroku#306]
http://www.vagrantbox.es/ reads "last updated on May 20th, 2014", but includes https://github.com/garethr/vagrantboxes-heroku/commit/e7e750ef6dc15fb07179abdc214d4bf210ba2a6c (search for "2014-06-20" on vagrantbox.es).

Probably the date needs an update.

**Comment by JonTheNiceGuy** [comment]
Removed from the current site.
