### ISSUE TITLE
Vagrantbox for SLES 11 SP3

### ISSUE THREAD

**Issue by carcarlo** [garethr/vagrantboxes-heroku#351]
Is this box http://www.benden.us/vagrant/sles11sp3.box active?

Can someone create one SLES 11 SP3 box? 

Thanks in advice
Carlo

**Comment by JonTheNiceGuy** [comment]
Hi Carlo, I'm getting a 404 on that URL too. I'm afraid we're just a register of publicly accessible boxes, and we're not in the position to create and host boxes.

Going back to the SLES11SP3 box, @jbenden have you taken the box offline? If so, would you be able to create a PR to remove them from the register, or failing that, let me know and I'll remove it?

**Comment by jbenden** [comment]
I changed a Varnish setting that rendered them 404'd. I fixed it and
they should be just fine now. Sorry for the problem!

Best Regards,
-Joe

JonTheNiceGuy writes:

>    Hi Carlo, I'm getting a 404 on that URL too. I'm afraid we're just a
>    register of publicly accessible boxes, and we're not in the position to
>    create and host boxes.
>
>    Going back to the SLES11SP3 box, [1]@jbenden have you taken the box
>    offline? If so, would you be able to create a PR to remove them from the
>    register, or failing that, let me know and I'll remove it?
>
>    --
>    Reply to this email directly or [2]view it on GitHub.
>
>    Reverse link: [3]unknown
>
> References
>
>    Visible links
>    1. https://github.com/jbenden
>    2. https://github.com/garethr/vagrantboxes-heroku/issues/351#issuecomment-73020446
>    3. https://github.com/garethr/vagrantboxes-heroku/issues/351#issuecomment-73020446

--
Sent with my mu4e

**Comment by JonTheNiceGuy** [comment]
@carcarlo does that solve this for you? If so, please can you close this issue?

**Comment by carcarlo** [comment]
@JonTheNiceGuy I'm able to dowload the box now, but the start up process stalled in vagrant.

**Comment by JonTheNiceGuy** [comment]
I'm glad to hear you were able to obtain the image. I'll therefore close this issue.
