### ISSUE TITLE
django boxes return 404 for url 

### ISSUE THREAD

**Issue by albertrosa** [garethr/vagrantboxes-heroku#355]
As I was attempting to install these boxes they returned a 404.

http://devopera.com/node/8/download/ubuntu1204/dobu12-dj1off-vagrant.box
http://devopera.com/node/8/download/centos6/doco6-dj1off-vagrant.box

**Comment by JonTheNiceGuy** [comment]
These were added to the index by @cleverlight. @cleverlight, are you the owner of these links, or did you find them online? 

If you're the owner, would you be able to raise a PR to get the new URLs in the index? It looks like they've moved to http://devopera.com/node/8/download/ubuntu1204 and http://devopera.com/node/8/download/centos6 but I don't know if these are the canonical URLs for the new locations? If you just found them, let me know and I'll try to talk to the devopera team at some point this week or next.

**Comment by cleverlight** [comment]
I've fixed the links.  My apologies for the outage.

**Comment by JonTheNiceGuy** [comment]
@albertrosa Thanks to the awesomeness of @cleverlight, I'll close this now :)

**Comment by albertrosa** [comment]
Thanks a bunch guys! Very much appreciated.
