### ISSUE TITLE
some box is broken in the list

### ISSUE THREAD

**Issue by sunstudy** [garethr/vagrantboxes-heroku#356]
https://dl.dropboxusercontent.com/s/srw2tqh58507wik/CentOS7.box
cannot open this link

**Comment by JonTheNiceGuy** [comment]
Hi @sunstudy unfortunately the way that Dropbox works means that if you have too many people using your box image, it will return an HTTP 509 error. I have just checked this URL and it is, sadly, returning this code.

@wingZero21 this is a box you've submitted. Would you be able to help at all?

**Comment by sunstudy** [comment]
@JonTheNiceGuy  the error is 509, what aboutyou?

**Comment by JonTheNiceGuy** [comment]
Same for me.

**Comment by holms** [comment]
Just remove it :) I've added latest centos which even has a template into the list :) 

* Here's template: https://github.com/holms/vagrant-centos7-box 
* Here's box: https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box

Feel free to contribute if you think initial setup is wrong.

**Comment by JonTheNiceGuy** [comment]
@sunstudy given I've had no response from @wingZero21 and @holms has suggested using his CentOS box, are you happy for me to close this Issue? I'm reluctant to remove a box entry that is not "gone" but is responding excessive bandwidth use.

**Comment by wingZero21** [comment]
Hey, 

Yeah feel free to drop it, annoying with the bandwidth restrictions on dropbox!!!

**Comment by holms** [comment]
@JonTheNiceGuy feel free to close this issue :+1: 
@wingZero21 yeah that's why there's vagrant cloud, and github repositories for :) (Release section!)

**Comment by JonTheNiceGuy** [comment]
Oops, misread the text - I still need to remove the box from the index.
