### ISSUE TITLE
The su password required to install postgresql

### ISSUE THREAD

**Issue by nicolasrenon** [garethr/vagrantboxes-heroku#365]
Hello.

I've downloaded the Debian 7.8.0 (based on amd64 netinst iso file) box from Vagrantbox.es list and I am using it successfully for a Rails app. But now I need to switch from sqlite3 to postgresql.

Following the documentation on https://wiki.debian.org/PostgreSql I have to use this command before accessing the psql console :

```
su - postgres
```

Unfortunately the password is needed :

```
vagrant@vagrant-debian-wheezy:~$ su - postgres
Password: 
su: Authentication failure
```

Do you any idea of what the password could be please?

**Comment by JonTheNiceGuy** [comment]
Thanks for the ticket @nicolasrenon. Vagrantbox.es is just an index of public boxes, and we don't have detailed instructions for the boxes which are there. You'll need to speak to the author of the box.

That said, the typical method of changing privileges in a Debian box is to use the sudo command to go via root (like this `sudo su - postgres` or `sudo -i` to become root, and then `su - postgres`).

I hope this helps. I'll close the ticket, as it's not actually related to the Vagrantbox.es project, but feel free to use this ticket to pursue further help :)

**Comment by nicolasrenon** [comment]
Thank you for your quick reply.
Sorry for the misunderstanding, I thought vagrantbox.es "edited" all the boxes.

BTW your sudo command did the job, thank you again ;)
