### ISSUE TITLE
how to the box default password?

### ISSUE THREAD

**Issue by heidsoft** [garethr/vagrantboxes-heroku#380]
box password i don't know

**Comment by JonTheNiceGuy** [comment]
Hi @heidsoft, Thanks for getting in touch, but I'm not sure how much help I can be.

Each box on this list is contributed by someone outside the team who maintain this list. You would need to contact the creator of those boxes should the below guidance not work.

By default, Vagrant uses a public/private key pair to SSH into the box, and the people who create the boxes have a common convention of using the word "vagrant" as both username and password.

As this isn't something we can help you with directly, I'll close this issue, but if you have any further questions, please feel free to discuss it in the comments here.

**Comment by heidsoft** [comment]
thank you,I found, root CentOS I can go in, but Ubuntu can not enter

**Comment by heidsoft** [comment]
@JonTheNiceGuy thank you.I found, root CentOS I can go in, but Ubuntu can not enter

**Comment by JonTheNiceGuy** [comment]
Once you've got the Vagrant box started, with `vagrant up` you then run `vagrant ssh` and it brings you into the box. Once you're in, type `sudo -i` to become root. You can then set passwords, create users etc.
