### ISSUE TITLE
flash usage

### ISSUE THREAD

**Issue by treaki** [garethr/vagrantboxes-heroku#394]
hi,

on the page http://www.vagrantbox.es/ a propitiatory non standardized technology [01] for an purpurse wherefore it isn't necessary. There are grate ways [02] to lighten the access to the system clipboard using free and open technologies. 
So please fix that!!!

annotations:
01: adobe flash
02: using html/javascript/css

**Comment by JonTheNiceGuy** [comment]
Hi @treaki, thanks for the comment. Please feel free to submit a PR suggesting how to fix this? This is a community index, and we've been more than happy to replace out infrastructure in the past, so if you know of a better Javascript library (than the one we're currently using) or some lines of HTML and CSS we can use to copy a line of text automatically to the clipboard, then that would be awesome! I've have recently heard of [clipboard.js](http://zenorocha.github.io/clipboard.js/) which might be appropriate, but as this is just a something-I-do-to-help-out-the-community-thing I don't get a lot of time to invest in it, so although I'm sure that this might read like I'm brushing you off, the honest truth is I'd love to see this replaced in, so I really would welcome a PR.

If you need any help with that, come back to this issue (which, I should note, I'm closing - I acknowledge there's a request for this, but until I've got something usable, I can't do anything with this) and let me know what you need help with, and I'll do what I can!

All the best,

JonTheNiceGuy
