### ISSUE TITLE
ssh doesn't connect, Kali Linux Vagrant Image

### ISSUE THREAD

**Issue by heticor915** [garethr/vagrantboxes-heroku#407]
Hi,

After running the proper vagrant commands under Windows 10 x64(Cygwin) it seems that there is a problem to connect via ssh running `vagrant ssh `, See images below, I've tested all the default users posible, can anybody confirm if it's necesary a special ssh configuration, and what's the proper user name port. 

![Installation of Box](http://i.imgur.com/OCnbMar.png)
![Failure Lauching Ssh](http://i.imgur.com/q6U0rTQ.png)

Thanks in Advance,
Hector F. J.

**Comment by JonTheNiceGuy** [comment]
Hey @heticor915. This box was added in #160 by @crm114. It comes from https://www.github.com/sliim/pentest-env

Unfortunately, we only host an index of available boxes and we can't support the box files themselves. Having done some playing with Kali in the past, [you might find that the username of "root" has a default password of "toor" (root backwards)](http://docs.kali.org/introduction/kali-linux-default-passwords).

Hope this helps, but if not, please raise an issue on the sliim/pentest-env repo.

Thanks!

**Comment by heticor915** [comment]
Hi @JonTheNiceGuy , 

Well I haven't tested yet but as I mentioned in my issue I test the default user and password that you mention , as a sugestion I think that if somebody else choose the Kali Linux vagrant image, you should mention where it comes and where is it from in vagrantbox.es 

So I will check later.
Regards, 
Hector F. J.

**Comment by Sliim** [comment]
Hi @heticor915,

Kali boxes that comes with [pentest-env](https://github.com/Sliim/pentest-env) are packaged with this private key: https://github.com/Sliim/pentest-env/blob/master/ssh-keys/pentest-env

In your `Vagrantfile`, you need to specify the private key path:
```
kali.ssh.private_key_path = 'ssh-keys/pentest-env'
```

Also I recommend you to use my latest boxes (Kali 2.0)

The best way to use these boxes is to use the [pentest-env](https://github.com/Sliim/pentest-env) repo, or look at https://github.com/Sliim/pentest-env/blob/master/Vagrantfile.
