### ISSUE TITLE
Login invalid

### ISSUE THREAD

**Issue by LuanMaik** [garethr/vagrantboxes-heroku#432]
I get download from:
https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box 
but the login doesn't work, 
I've got tried :

User: vagrant
Pass: vagrant

User: ubuntu
Pass: ubuntu

I've got tried in camel case, but doesn't work.

Do Somebody knows the right login?

**Comment by JonTheNiceGuy** [comment]
Hi, this isn't an issue for vagrantbox.es but it's actually the box file as created by Canonical. If you check in .vagrant.d/boxes/what-the-box-you-imported-is-called/SomeSubdirectory/Vagrantfile it will list the password in there. It's basically a 16 character sequence of hex characters. Personally, I change it on boot. See https://github.com/JonTheNiceGuy/K5-Ansible-Openstack-Development-Machine/blob/master/ansible_users.yml for how I personally do it (you may want to do it differently)

**Comment by LuanMaik** [comment]
I opened the .box file with winrar and I found the password into Vagrantfile, thanks for helping
