### ISSUE TITLE
Missing metadata.json

### ISSUE THREAD

**Issue by JapE1337** [garethr/vagrantboxes-heroku#434]
Hi,
I'm trying to add the win7-ie9 box. 
But when I run the add command, I'm getting this error: 
![image](https://user-images.githubusercontent.com/37000366/43035063-ce56b868-8ce8-11e8-8da9-2a12026d08dd.png)

**Comment by JonTheNiceGuy** [comment]
Hi, this isn't something we can help with, sadly. It's just an index of boxes. You would need to contact the owner of that box directly.

**Comment by JapE1337** [comment]
Oh okay :/ 
Do you know the where i can get in contact with that person?

**Comment by JonTheNiceGuy** [comment]
So, normally, I'd be able to say "Oh yes, here's the pull request that added it in, pester them"... except... none of the links in that pull request are working, so I think it might be dead :(

I'd say check in with MS, but I'm not sure they're still sharing them, are they? Well, they kinda are, but only Win10 with Edge :( (https://app.vagrantup.com/Microsoft/boxes/EdgeOnWindows10)
