### ISSUE TITLE
Add Debian 9 in the list

### ISSUE THREAD

**Issue by borrougagnou** [garethr/vagrantboxes-heroku#435]
Hi !
He exist only Debian 8, not Debian 9...
can you add support for this OS please ?
VirtualBox and maybe VMWare (latest VMware box actually in the list: Debian 7.5)

**Comment by JonTheNiceGuy** [comment]
Hi there. Unfortunately, this project is only an index of public boxes that people have provided to us. At the moment, no one has provided box details for Debian 9.
